services:
  fastapi:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    container_name: rag_fastapi
    ports:
      - "8000:8000"
    env_file:
      - /mnt/z/SnowCode/RAGCONTENT/.env
    environment:
      - PYTHONPATH=/app/src
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - GEMINI_API_KEY=${GEMINI_API_KEY}
      - PINECONE_API_KEY=${PINECONE_API_KEY}
      - REDIS_URL=redis://redis:6379/0
    depends_on:
      - redis
    volumes:
      - ./src:/app/src


  celery_worker:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    container_name: rag_celery
    command: celery -A src.tasks worker --loglevel=info
    env_file:
      - /mnt/z/SnowCode/RAGCONTENT/.env
    environment:
      - PYTHONPATH=/app/src
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - GEMINI_API_KEY=${GEMINI_API_KEY}
      - PINECONE_API_KEY=${PINECONE_API_KEY}
      - REDIS_URL=redis://redis:6379/0
    depends_on:
      - redis
    volumes:
      - ./src:/app/src


  redis:
    image: redis:7-alpine
    container_name: rag_redis
    ports:
      - "6379:6379"
